# GitAI Configuration File
# Copy this file to .gitcommit.yaml and customize it for your project

# Ollama model to use for generating commit messages
# Popular options: qwen2.5-coder:7b, mistral:7b, codellama:7b
model: "qwen2.5-coder:7b"

# Language Configuration
# =====================

# Single language mode: Set language to your preferred language code
# Supported: en (English), zh (Chinese), ja (Japanese), ko (Korean),
#           de (German), fr (French), es (Spanish), pt (Portuguese),
#           ru (Russian), it (Italian)
language: "en"

# Multilingual mode: Uncomment 'languages' to generate commit messages in multiple languages
# The first language is the primary language for the subject line
# Additional languages will be included as translations in the commit body
# languages:
#   - "en"  # Primary language (English)
#   - "zh"  # Add Chinese translation
#   - "ja"  # Add Japanese translation

# Auto-detect language from project (README, commits, documentation)
# If enabled, GitAI will analyze your project to determine the appropriate language
# This setting is ignored if 'languages' (multilingual mode) is set
# auto_detect_language: true

# Commit message template
# Available variables: {type}, {scope}, {emoji}, {message}
template: "{type}{scope}: {emoji} {message}"

# Maximum length of git diff to send to AI (in characters)
max_diff_length: 2000

# Generate detailed commit messages with body (recommended: true)
# If true: generates multi-line commits with subject + body explaining changes
# If false: generates concise single-line commits (subject only)
detailed_commit: true

# Subject line length (short or normal)
# short: max 36 characters - for very concise commit messages
# normal: max 72 characters - standard conventional commits length (default)
subject_length: "normal"

# Scope prompt configuration
# Set to true to prompt for scope selection interactively
# Set to false (default) to skip scope prompt
# Note: You can always provide scope via --scope flag or use --prompt-scope flag
prompt_scope: false

# Ticket/Issue number configuration
# Enable if your team requires ticket numbers in commits (e.g., Jira, GitHub issues)
require_ticket: false                  # Set to true to make ticket number mandatory
ticket_prefix: ""                      # Default prefix (e.g., "JIRA", "PROJ", "GH")
ticket_pattern: ""                     # Regex pattern to extract from branch (e.g., "[A-Z]+-\\d+")

# Examples:
# For Jira integration:
#   require_ticket: true
#   ticket_prefix: "PROJ"
#   ticket_pattern: "[A-Z]+-\\d+"     # Matches PROJ-123, JIRA-456
#
# For GitHub issues:
#   require_ticket: true
#   ticket_prefix: "GH"
#   ticket_pattern: "#\\d+|GH-\\d+"   # Matches #123 or GH-123

# Predefined commit types following Conventional Commits
types:
  - name: "feat"
    desc: "A new feature"
    emoji: "✨"

  - name: "fix"
    desc: "A bug fix"
    emoji: "🐛"

  - name: "docs"
    desc: "Documentation only changes"
    emoji: "📝"

  - name: "style"
    desc: "Code style changes (formatting, missing semicolons, etc)"
    emoji: "💄"

  - name: "refactor"
    desc: "Code refactoring (neither fixes a bug nor adds a feature)"
    emoji: "♻️"

  - name: "perf"
    desc: "Performance improvements"
    emoji: "⚡"

  - name: "test"
    desc: "Adding or updating tests"
    emoji: "✅"

  - name: "chore"
    desc: "Build process or auxiliary tool changes"
    emoji: "🔧"

  - name: "ci"
    desc: "CI configuration changes"
    emoji: "👷"

  - name: "build"
    desc: "Changes that affect the build system or dependencies"
    emoji: "📦"

# Project-specific scopes (optional)
# If empty, user will be prompted to enter custom scope
scopes:
  - "api"
  - "ui"
  - "auth"
  - "db"
  - "config"
  - "docs"

# Custom commit guidelines (IMPORTANT - Company/Team Standards)
# Paste your company's commit message requirements here
# The AI will follow these guidelines strictly when generating commits
#
# Examples of what you can put here:
# - Your company's commit message template
# - Required format or structure
# - Mandatory fields (ticket numbers, reviewers, etc.)
# - Naming conventions
# - Special requirements (emojis, prefixes, etc.)
#
custom_prompt: |
  Follow our team's commit message guidelines:
  - Use imperative mood (e.g., "add" not "added")
  - Focus on the "why" and business impact, not the "how"
  - Keep subject line under 72 characters
  - Use present tense

  # Example: If your company requires ticket numbers, add:
  # - Include Jira ticket number: [PROJ-123]
  # - Format: <type>(<scope>): [TICKET] <description>

  # Example: If your company uses specific prefixes:
  # - Backend changes must use prefix: [BE]
  # - Frontend changes must use prefix: [FE]

  # Example: If your company requires specific sections:
  # - Must include "Business Impact:" section
  # - Must include "Testing:" section with test coverage info
